on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - run: echo some content >output.txt
      
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: output.txt
        
  deploy:
    needs: build
    environment: ${{ github.event.release.target_commitish }}
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        
    - run: cat output.txt
